# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/paulgrau/projects/aergo/aergo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/paulgrau/projects/aergo/aergo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/paulgrau/projects/aergo/aergo/CMakeFiles /Users/paulgrau/projects/aergo/aergo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/paulgrau/projects/aergo/aergo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named protoclean

# Build rule for target.
protoclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protoclean
.PHONY : protoclean

# fast build rule for target.
protoclean/fast:
	$(MAKE) -f CMakeFiles/protoclean.dir/build.make CMakeFiles/protoclean.dir/build
.PHONY : protoclean/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named protoc

# Build rule for target.
protoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protoc
.PHONY : protoc

# fast build rule for target.
protoc/fast:
	$(MAKE) -f CMakeFiles/protoc.dir/build.make CMakeFiles/protoc.dir/build
.PHONY : protoc/fast

#=============================================================================
# Target rules for targets named cover-check

# Build rule for target.
cover-check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cover-check
.PHONY : cover-check

# fast build rule for target.
cover-check/fast:
	$(MAKE) -f CMakeFiles/cover-check.dir/build.make CMakeFiles/cover-check.dir/build
.PHONY : cover-check/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named aergocli

# Build rule for target.
aergocli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aergocli
.PHONY : aergocli

# fast build rule for target.
aergocli/fast:
	$(MAKE) -f CMakeFiles/aergocli.dir/build.make CMakeFiles/aergocli.dir/build
.PHONY : aergocli/fast

#=============================================================================
# Target rules for targets named deps

# Build rule for target.
deps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deps
.PHONY : deps

# fast build rule for target.
deps/fast:
	$(MAKE) -f CMakeFiles/deps.dir/build.make CMakeFiles/deps.dir/build
.PHONY : deps/fast

#=============================================================================
# Target rules for targets named brick

# Build rule for target.
brick: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brick
.PHONY : brick

# fast build rule for target.
brick/fast:
	$(MAKE) -f CMakeFiles/brick.dir/build.make CMakeFiles/brick.dir/build
.PHONY : brick/fast

#=============================================================================
# Target rules for targets named aergoluac

# Build rule for target.
aergoluac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aergoluac
.PHONY : aergoluac

# fast build rule for target.
aergoluac/fast:
	$(MAKE) -f CMakeFiles/aergoluac.dir/build.make CMakeFiles/aergoluac.dir/build
.PHONY : aergoluac/fast

#=============================================================================
# Target rules for targets named aergosvr

# Build rule for target.
aergosvr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aergosvr
.PHONY : aergosvr

# fast build rule for target.
aergosvr/fast:
	$(MAKE) -f CMakeFiles/aergosvr.dir/build.make CMakeFiles/aergosvr.dir/build
.PHONY : aergosvr/fast

#=============================================================================
# Target rules for targets named vendor

# Build rule for target.
vendor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vendor
.PHONY : vendor

# fast build rule for target.
vendor/fast:
	$(MAKE) -f CMakeFiles/vendor.dir/build.make CMakeFiles/vendor.dir/build
.PHONY : vendor/fast

#=============================================================================
# Target rules for targets named build

# Build rule for target.
build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build
.PHONY : build

# fast build rule for target.
build/fast:
	$(MAKE) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build
.PHONY : build/fast

#=============================================================================
# Target rules for targets named libluajit-clean

# Build rule for target.
libluajit-clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libluajit-clean
.PHONY : libluajit-clean

# fast build rule for target.
libluajit-clean/fast:
	$(MAKE) -f libtool/CMakeFiles/libluajit-clean.dir/build.make libtool/CMakeFiles/libluajit-clean.dir/build
.PHONY : libluajit-clean/fast

#=============================================================================
# Target rules for targets named libtool-clean

# Build rule for target.
libtool-clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtool-clean
.PHONY : libtool-clean

# fast build rule for target.
libtool-clean/fast:
	$(MAKE) -f libtool/CMakeFiles/libtool-clean.dir/build.make libtool/CMakeFiles/libtool-clean.dir/build
.PHONY : libtool-clean/fast

#=============================================================================
# Target rules for targets named liblmdb-clean

# Build rule for target.
liblmdb-clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 liblmdb-clean
.PHONY : liblmdb-clean

# fast build rule for target.
liblmdb-clean/fast:
	$(MAKE) -f libtool/CMakeFiles/liblmdb-clean.dir/build.make libtool/CMakeFiles/liblmdb-clean.dir/build
.PHONY : liblmdb-clean/fast

#=============================================================================
# Target rules for targets named liblmdb

# Build rule for target.
liblmdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 liblmdb
.PHONY : liblmdb

# fast build rule for target.
liblmdb/fast:
	$(MAKE) -f libtool/CMakeFiles/liblmdb.dir/build.make libtool/CMakeFiles/liblmdb.dir/build
.PHONY : liblmdb/fast

#=============================================================================
# Target rules for targets named libluajit

# Build rule for target.
libluajit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libluajit
.PHONY : libluajit

# fast build rule for target.
libluajit/fast:
	$(MAKE) -f libtool/CMakeFiles/libluajit.dir/build.make libtool/CMakeFiles/libluajit.dir/build
.PHONY : libluajit/fast

#=============================================================================
# Target rules for targets named libtool

# Build rule for target.
libtool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtool
.PHONY : libtool

# fast build rule for target.
libtool/fast:
	$(MAKE) -f libtool/CMakeFiles/libtool.dir/build.make libtool/CMakeFiles/libtool.dir/build
.PHONY : libtool/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... protoclean"
	@echo "... distclean"
	@echo "... protoc"
	@echo "... cover-check"
	@echo "... check"
	@echo "... aergocli"
	@echo "... deps"
	@echo "... brick"
	@echo "... edit_cache"
	@echo "... aergoluac"
	@echo "... aergosvr"
	@echo "... vendor"
	@echo "... build"
	@echo "... libluajit-clean"
	@echo "... libtool-clean"
	@echo "... liblmdb-clean"
	@echo "... liblmdb"
	@echo "... libluajit"
	@echo "... libtool"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

